### ISSUE TITLE
 (reading 'IDL1Q9M1JE11SA50')

### ISSUE THREAD

**Issue by imranshahid790** [HansSchouten/PHPageBuilder#112]
app.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'IDL1Q9M1JE11SA50')
    at e (app.js:1:4166)
    at app.js:1:4397
    at Function.m.each.m.forEach (underscore.js:186:9)
    at r.each (backbone.js:87:18)
    at e (app.js:1:4373)
    at window.activateLanguage (app.js:1:7411)
    at t (app.js:1:3984)
    at e (app.js:1:12756)[]

when page builder edit  ... then show this error and page loader show only ...not get data....kindly solve as soon as possible

**Comment by HansSchouten** [comment]
I don't receive this issue, it is working fine on multiple websites. It is probably triggering here https://github.com/HansSchouten/PHPageBuilder/blob/master/src/Modules/GrapesJS/resources/assets/js/manage-editable-components.js#L105.
What does your page look like, what blocks are you using? It probably fails on a <script> or [phpb-content-container] tag

**Comment by imranshahid790** [comment]
thanks this issues is resolve...:)

..but one issue is pending....in edit page builder image resizing block not
showing.....plz kindly solve this issue
