### ISSUE TITLE
error after installation

### ISSUE THREAD

**Issue by bea545lisa** [HansSchouten/PHPageBuilder#175]
Hi , after editing config.php and accessing website I got this error message. What could be the problem?

Fatal error: Uncaught PDOException: could not find driver in /mnt/web015/xxx/htdocs/phpagebuilder/vendor/hansschouten/phpagebuilder/src/Core/DB.php:32 Stack trace: #0 /mnt/web015/xxx/htdocs/phpagebuilder/vendor/hansschouten/phpagebuilder/src/Core/DB.php(32): PDO->__construct() #1 /mnt/web015/xxx/htdocs/phpagebuilder/vendor/hansschouten/phpagebuilder/src/PHPageBuilder.php(144): PHPageBuilder\Core\DB->__construct() #2 /mnt/web015/xxx/htdocs/phpagebuilder/vendor/hansschouten/phpagebuilder/src/PHPageBuilder.php(70): PHPageBuilder\PHPageBuilder->setDatabaseConnection() #3 /mnt/web015/xxx/htdocs/phpagebuilder/index.php(15): PHPageBuilder\PHPageBuilder->__construct() #4 {main} thrown in /mnt/web015/xxx/htdocs/phpagebuilder/vendor/hansschouten/phpagebuilder/src/Core/DB.php on line 32

**Comment by EhabAmawi** [comment]
@bea545lisa 
that means that you don't have the DB driver installed on your machine.
