### ISSUE TITLE
Error creating the page

### ISSUE THREAD

**Issue by Vanguger** [HansSchouten/PHPageBuilder#4]
Finally, I was able to launch the Manager. But the following error occurred when creating the page:
**url:** site/admin?route=page_settings&action=create

**Fatal error:** Uncaught PDOException: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '0000-00-00 00:00:00' for column 'created_at' at row 1 in D:\OSPanel\domains\ppb.test\src\Core\DB.php:106 Stack trace: #0 D:\OSPanel\domains\ppb.test\src\Core\DB.php(106): PDOStatement->execute(Array) #1 D:\OSPanel\domains\ppb.test\src\Repositories\BaseRepository.php(61): PHPageBuilder\Core\DB->query('INSERT INTO pag...', Array) #2 D:\OSPanel\domains\ppb.test\src\Repositories\PageRepository.php(51): PHPageBuilder\Repositories\BaseRepository->create(Array) #3 D:\OSPanel\domains\ppb.test\src\Modules\WebsiteManager\WebsiteManager.php(59): PHPageBuilder\Repositories\PageRepository->create(Array) #4 D:\OSPanel\domains\ppb.test\src\Modules\WebsiteManager\WebsiteManager.php(32): PHPageBuilder\Modules\WebsiteManager\WebsiteManager->handleCreate() #5 D:\OSPanel\domains\ppb.test\src\PHPageBuilder.php(245): PHPageBuilder\Modules\WebsiteManager\WebsiteManager->handleRequest('page_settings', 'create') #6 D:\OSPanel\domains\ppb. in **D:\OSPanel\domains\ppb.test\src\Core\DB.php on line 106**

**Comment by Vanguger** [comment]
I was able to solve this problem by changing the field in the database:
**pages > create_at > default > CURRENT_TIMESTAMP**
